import { Inter } from "next/font/google";
import "@/app/_styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Netflix",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<header></header>
				<main>{children}</main>
				<footer></footer>
			</body>
		</html>
	);
}
